# This is a basic workflow to help you get started with Actions

name: VascoTweetApi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: main
  schedule:
    - cron: "00 02 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vascotweet-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("rtweet", "dplyr", "qdapRegex", "here", "R.utils", "stringi", "stringr", "tm", "wordcloud2", "htmlwidgets", "webshot"))'
      - name: Create and post tweet
        run: Rscript R/script.R
